# 项目相关配置
lemon:
  # 名称
  name: Lemon-Vue-Plus
  # 版本
  version: ${revision}
  # 版权年份
  copyrightYear: 2024

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

# Spring配置
spring:
  application:
    name: ${lemon.name}
  profiles:
    active: @profiles.active@


# 日志配置
logging:
  level:
    com.lemon: @logging.level@
    org.springframework: warn
    org.mybatis.spring.mapper: error
  config: classpath:logback-plus.xml


# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  # 多包名使用 例如 com.lemon.**.mapper,org.xxx.**.mapper
  mapperPackage: com.lemon.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lemon.**.domain
  global-config:
    dbConfig:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      # 如需改为自增 需要将数据库表全部设置为自增
      idType: ASSIGN_ID