# 项目相关配置
lemon:
  # 名称
  name: Lemon-Vue-Plus
  # 版本
  version: ${revision}
  # 版权年份
  copyrightYear: 2024

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

# Spring配置
spring:
  application:
    name: ${lemon.name}
  profiles:
    active: @profiles.active@


# 日志配置
logging:
  level:
    com.lemon: @logging.level@
    org.springframework: warn
    org.mybatis.spring.mapper: error
  config: classpath:logback-plus.xml