# 项目相关配置
lemon:
  # 名称
  name: Lemon-Vue-Plus
  # 版本
  version: ${revision}
  # 版权年份
  copyrightYear: 2024

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /